from __future__ import annotations

from typing import Any
from zoneinfo import ZoneInfo

LOCAL_TZ = ZoneInfo("America/Sao_Paulo")
BENCHMARK_SYMBOL = "XB1"
LEG_DEFINITION_VERSION = 5


DEFAULT_LEG_DEFINITIONS: list[dict[str, Any]] = [
    {
        "key": "credit",
        "label": "Credito",
        "layer": "core",
        "default_visible": True,
        "assets": [
            "BRAZIL CDS USD SR 5Y D14",
            "BRAZIL CDS USD SR 3Y D14",
            "CDX EM CDSI S44 5Y PRC",
            "CDX HY CDSI GEN 5Y SPRD",
            "CDX IG CDSI GEN 5Y",
            "EMBIV",
            "EMHY CDSI S44 5Y PRC",
        ],
    },
    {
        "key": "equity_foreign",
        "label": "Equity Estrangeiro",
        "layer": "core",
        "default_visible": True,
        "assets": [
            "ESA",
            "RTYA",
            "DMA",
            "EEM US",
        ],
    },
    {
        "key": "equity_local",
        "label": "Equity Local",
        "layer": "core",
        "default_visible": True,
        "assets": [
            "EWZ US",
            "IFNCBV",
            "IMAT",
            "ICON",
            "IDIV",
            "SMALL11",
        ],
    },
    {
        "key": "commodities",
        "label": "Commodities",
        "layer": "core",
        "default_visible": True,
        "assets": ["HG1", "IOE1", "CLA", "SCOA", "BCOM"],
    },
    {
        "key": "fx",
        "label": "FX",
        "layer": "core",
        "default_visible": True,
        "assets": ["WD01", "DXY", "MXN", "ZAR", "CNH", "CLP", "AUD"],
    },
    {
        "key": "funding",
        "label": "Funding",
        "layer": "core",
        "default_visible": True,
        "assets": [
            ".BRII1Y",
            ".BRII2Y",
            ".BRII5Y",
            ".BRII10Y",
            "USGG2YR",
            "USGG10YR",
            "USSO2",
            "USSO10",
            "USOSFR1 BGN",
            "USOSFR5 BGN",
            "USOSFR10 BGN",
            "USGGBE05",
            "USGGBE10",
        ],
    },
    {
        "key": "di",
        "label": "DIs",
        "layer": "core",
        "default_visible": True,
        "assets": [
            "ODF27",
            "ODF28",
            "ODF29",
            "ODF30",
            "ODF31",
            "ODF32",
            "ODF33",
            "ODF35",
        ],
    },
    {
        "key": "risk",
        "label": "Risco",
        "layer": "shadow",
        "default_visible": True,
        "assets": ["VIX", "VIX3M", "VXBR", "OVX", "WVIX"],
    },
    {
        "key": "sentiment",
        "label": "Sentimento",
        "layer": "shadow",
        "default_visible": True,
        "assets": [
            ".BBR U",
            ".CBBR U",
            ".JPYB U",
            "DXY",
            "EWZ US",
            "EEM US",
            "BRAZIL CDS USD SR 5Y D14",
            "CDX EM CDSI S44 5Y PRC",
        ],
    },
]


RPC_COMPONENT_DEFINITIONS_V1: list[dict[str, Any]] = [
    {
        "key": "di_slope",
        "label": "DI slope",
        "kind": "slope",
        "base_weight": 1.15,
        "short_symbols": ["ODF27", "ODF28", "ODF29"],
        "long_symbols": ["ODF31", "ODF32", "ODF33", "ODF35"],
        "sign": -1.0,
        "description": "DI steepening/inclinacao subindo contributes negatively to RPC.",
    },
    {
        "key": "di_oi",
        "label": "DI OI",
        "kind": "unavailable",
        "base_weight": 0.0,
        "symbols": [],
        "description": "DI open interest is not present in the saved W32 rows; kept as explicit missing component.",
    },
    {
        "key": "treasury",
        "label": "Treasuries",
        "kind": "basket",
        "base_weight": 1.05,
        "symbols": ["USGG2YR", "USGG10YR", "USGGT02Y", "USGGT10Y", "USGG5Y5Y"],
        "sign": 1.0,
        "description": "Higher US yields are treated as global funding/risk pressure.",
    },
    {
        "key": "bbr",
        "label": "BBR",
        "kind": "basket",
        "base_weight": 0.95,
        "symbols": [".BBR U"],
        "sign": -1.0,
        "description": "Brazil sovereign dollar bond basket: price down means pressure up.",
    },
    {
        "key": "cbbr",
        "label": "CBBR",
        "kind": "basket",
        "base_weight": 0.85,
        "symbols": [".CBBR U"],
        "sign": -1.0,
        "description": "Brazil corporate dollar bond basket: price down means pressure up.",
    },
    {
        "key": "cdx_em",
        "label": "CDX EM",
        "kind": "basket",
        "base_weight": 1.10,
        "symbols": ["CDX EM CDSI S44 5Y PRC", "EMHY CDSI S44 5Y PRC"],
        "sign": 1.0,
        "description": "CDX EM up contributes positively to RPC.",
    },
    {
        "key": "cdx_hy",
        "label": "CDX HY",
        "kind": "basket",
        "base_weight": 1.00,
        "symbols": ["CDX HY CDSI GEN 5Y SPRD"],
        "sign": -1.0,
        "description": "CDS HY up contributes negatively to RPC.",
    },
    {
        "key": "vixbr",
        "label": "VIXBR",
        "kind": "basket",
        "base_weight": 1.10,
        "symbols": ["VXBR", "VIX", "VIX3M", "WVIX"],
        "sign": -1.0,
        "description": "VXBR/volatility up contributes negatively to RPC.",
    },
]


RPC_COMPONENT_DEFINITIONS_V2: list[dict[str, Any]] = [
    {
        "key": "di_slope",
        "label": "DI slope",
        "kind": "slope",
        "base_weight": 1.15,
        "target_weight": 0.27,
        "score_mode": "signed_raw",
        "score_scale": 0.004,
        "short_symbols": ["ODF27", "ODF28", "ODF29"],
        "long_symbols": ["ODF31", "ODF32", "ODF33", "ODF35"],
        "sign": -1.0,
        "description": "DI steepening/inclinacao subindo contributes negatively to RPC.",
    },
    {
        "key": "di_oi",
        "label": "DI OI",
        "kind": "unavailable",
        "base_weight": 0.0,
        "symbols": [],
        "description": "DI open interest is not present in the saved W32 rows; kept as explicit missing component.",
    },
    {
        "key": "treasury_level",
        "label": "Treasuries level",
        "kind": "basket",
        "base_weight": 0.58,
        "target_weight": 0.045,
        "score_mode": "signed_raw",
        "score_scale": 0.006,
        "symbols": ["USGG2YR", "USGG10YR", "USGGT02Y", "USGGT10Y", "USGG5Y5Y"],
        "sign": -1.0,
        "description": "US yields down are supportive for the index; yields up are pressure.",
    },
    {
        "key": "treasury_slope",
        "label": "Treasuries slope",
        "kind": "slope",
        "base_weight": 0.57,
        "target_weight": 0.045,
        "score_mode": "signed_raw",
        "score_scale": 0.018,
        "short_symbols": ["USGG2YR", "USGGT02Y"],
        "long_symbols": ["USGG10YR", "USGGT10Y", "USGG5Y5Y"],
        "sign": -1.0,
        "description": "US curve steepening contributes negatively to RPC, mirroring the DI slope convention.",
    },
    {
        "key": "di_f30_plus",
        "label": "DI F30+ level",
        "kind": "basket",
        "base_weight": 0.60,
        "target_weight": 0.06,
        "score_mode": "signed_raw",
        "score_scale": 0.005,
        "symbols": ["ODF30", "ODF31", "ODF32", "ODF33", "ODF35"],
        "sign": -1.0,
        "description": "Own DI level variation from F30 onward; DI up is pressure, DI down is supportive for the index.",
    },
    {
        "key": "bbr",
        "label": "BBR",
        "kind": "basket",
        "base_weight": 0.95,
        "target_weight": 0.10,
        "score_mode": "signed_raw",
        "score_scale": 0.004,
        "symbols": [".BBR U"],
        "sign": 1.0,
        "description": "Brazil sovereign dollar bond basket: price up supports RPC; price down contributes negatively.",
    },
    {
        "key": "cbbr",
        "label": "CBBR",
        "kind": "basket",
        "base_weight": 0.85,
        "target_weight": 0.0875,
        "score_mode": "signed_raw",
        "score_scale": 0.004,
        "symbols": [".CBBR U"],
        "sign": 1.0,
        "description": "Brazil corporate dollar bond basket: price up supports RPC; price down contributes negatively.",
    },
    {
        "key": "cdx_em",
        "label": "CDX EM x5",
        "kind": "basket",
        "base_weight": 1.10,
        "target_weight": 0.0935,
        "score_mode": "signed_raw",
        "score_scale": 0.004,
        "symbols": ["CDX EM CDSI S44 5Y PRC"],
        "sign": 1.0,
        "scale": 5.0,
        "description": "CDX EM price variation is multiplied by 5 and kept positively correlated with the index.",
    },
    {
        "key": "cdx_hy",
        "label": "CDX HY",
        "kind": "basket",
        "base_weight": 1.00,
        "target_weight": 0.10,
        "score_mode": "signed_raw",
        "score_scale": 0.010,
        "symbols": ["CDX HY CDSI GEN 5Y SPRD"],
        "sign": -1.0,
        "description": "CDS HY up contributes negatively to RPC.",
    },
    {
        "key": "vixbr",
        "label": "VIXBR",
        "kind": "basket",
        "base_weight": 1.10,
        "target_weight": 0.20,
        "score_mode": "signed_raw",
        "score_scale": 0.030,
        "symbols": ["VXBR", "VIX", "VIX3M", "WVIX"],
        "symbol_aliases": {"WVIX": ["WIX"]},
        "sign": -1.0,
        "description": "VXBR/volatility up contributes negatively to RPC; WVIX may arrive as WIX.",
    },
]


RPC_COMPONENT_DEFINITIONS = RPC_COMPONENT_DEFINITIONS_V2
RPC_COMPONENT_VERSION_DEFINITIONS = (
    ("v1", RPC_COMPONENT_DEFINITIONS_V1),
    ("v2", RPC_COMPONENT_DEFINITIONS_V2),
)
